-- =====================================================
-- Hospital Management System - PostgreSQL Database Schema
-- =====================================================

-- Drop existing tables if they exist (for clean setup)
DROP TABLE IF EXISTS BILLING_PAYMENTS CASCADE;
DROP TABLE IF EXISTS INVOICE_ITEMS CASCADE;
DROP TABLE IF EXISTS INVOICES CASCADE;
DROP TABLE IF EXISTS APPOINTMENTS CASCADE;
DROP TABLE IF EXISTS PATIENT_BEDS CASCADE;
DROP TABLE IF EXISTS BEDS CASCADE;
DROP TABLE IF EXISTS ROOMS CASCADE;
DROP TABLE IF EXISTS MEDICAL_HISTORY CASCADE;
DROP TABLE IF EXISTS PATIENTS CASCADE;
DROP TABLE IF EXISTS DOCTOR_SCHEDULES CASCADE;
DROP TABLE IF EXISTS DOCTORS CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS ROLES CASCADE;
DROP TABLE IF EXISTS DEPARTMENTS CASCADE;

-- Update trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.UPDATED_AT = CURRENT_TIMESTAMP;
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- CREATE Custom Sequences
CREATE SEQUENCE IF NOT EXISTS SEQ_PATIENTS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_APPOINTMENTS START WITH 1 INCREMENT BY 1;

-- =====================================================
-- 1. ROLES TABLE
-- =====================================================
CREATE TABLE ROLES (
    ROLE_ID SERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255),
    PERMISSIONS TEXT, -- JSON array of permissions
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_roles_updated 
BEFORE UPDATE ON ROLES FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 2. DEPARTMENTS TABLE
-- =====================================================
CREATE TABLE DEPARTMENTS (
    DEPT_ID SERIAL PRIMARY KEY,
    DEPT_NAME VARCHAR(100) NOT NULL UNIQUE,
    DEPT_CODE VARCHAR(20) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(500),
    LOCATION VARCHAR(100),
    HEAD_DOCTOR_ID INT,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trg_departments_updated 
BEFORE UPDATE ON DEPARTMENTS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 3. USERS TABLE
-- =====================================================
CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    PHONE VARCHAR(20),
    ROLE_ID INT NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    LAST_LOGIN TIMESTAMP,
    EMAIL_VERIFIED INT DEFAULT 0,
    PROFILE_IMAGE VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)
);

CREATE TRIGGER trg_users_updated 
BEFORE UPDATE ON USERS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 4. DOCTORS TABLE
-- =====================================================
CREATE TABLE DOCTORS (
    DOCTOR_ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL UNIQUE,
    EMPLOYEE_ID VARCHAR(20) NOT NULL UNIQUE,
    SPECIALIZATION VARCHAR(100) NOT NULL,
    DEPT_ID INT,
    QUALIFICATION VARCHAR(500),
    EXPERIENCE_YEARS INT DEFAULT 0,
    CONSULTATION_FEE NUMERIC(10,2) DEFAULT 0,
    LICENSE_NUMBER VARCHAR(50) NOT NULL UNIQUE,
    JOINING_DATE DATE NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'ON_LEAVE')),
    RATING NUMERIC(2,1) DEFAULT 0 CHECK (RATING >= 0 AND RATING <= 5),
    PATIENTS_SEEN INT DEFAULT 0,
    BIO TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_DOCTORS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_DOCTORS_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID)
);

CREATE TRIGGER trg_doctors_updated 
BEFORE UPDATE ON DOCTORS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 5. DOCTOR_SCHEDULES TABLE
-- =====================================================
CREATE TABLE DOCTOR_SCHEDULES (
    SCHEDULE_ID SERIAL PRIMARY KEY,
    DOCTOR_ID INT NOT NULL,
    DAY_OF_WEEK INT NOT NULL CHECK (DAY_OF_WEEK BETWEEN 0 AND 6),
    START_TIME VARCHAR(5) NOT NULL, -- Format: HH24:MI
    END_TIME VARCHAR(5) NOT NULL,
    SLOT_DURATION INT DEFAULT 30, -- in minutes
    MAX_PATIENTS INT DEFAULT 10,
    IS_AVAILABLE INT DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SCHEDULE_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID) ON DELETE CASCADE
);

CREATE TRIGGER trg_doctor_schedules_updated 
BEFORE UPDATE ON DOCTOR_SCHEDULES FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 6. PATIENTS TABLE
-- =====================================================
CREATE TABLE PATIENTS (
    PATIENT_ID SERIAL PRIMARY KEY,
    PATIENT_CODE VARCHAR(20) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    GENDER VARCHAR(10) NOT NULL CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER')),
    BLOOD_GROUP VARCHAR(5),
    PHONE VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(100),
    ADDRESS VARCHAR(500),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    ZIP_CODE VARCHAR(20),
    EMERGENCY_CONTACT_NAME VARCHAR(100),
    EMERGENCY_CONTACT_PHONE VARCHAR(20),
    INSURANCE_PROVIDER VARCHAR(100),
    INSURANCE_NUMBER VARCHAR(50),
    ALLERGIES TEXT,
    CHRONIC_CONDITIONS TEXT,
    ASSIGNED_DOCTOR_ID INT,
    ADMISSION_DATE TIMESTAMP,
    DISCHARGE_DATE TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'OUTPATIENT' CHECK (STATUS IN ('INPATIENT', 'OUTPATIENT', 'DISCHARGED')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PATIENTS_DOCTOR FOREIGN KEY (ASSIGNED_DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID)
);

CREATE TRIGGER trg_patients_updated 
BEFORE UPDATE ON PATIENTS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 7. MEDICAL_HISTORY TABLE
-- =====================================================
CREATE TABLE MEDICAL_HISTORY (
    HISTORY_ID SERIAL PRIMARY KEY,
    PATIENT_ID INT NOT NULL,
    VISIT_DATE TIMESTAMP NOT NULL,
    DOCTOR_ID INT NOT NULL,
    DIAGNOSIS VARCHAR(1000),
    SYMPTOMS TEXT,
    PRESCRIPTION TEXT,
    NOTES TEXT,
    ATTACHMENTS TEXT, -- JSON array of file paths
    FOLLOW_UP_DATE TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_HISTORY_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_HISTORY_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID)
);

CREATE TRIGGER trg_medical_history_updated 
BEFORE UPDATE ON MEDICAL_HISTORY FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 8. ROOMS TABLE
-- =====================================================
CREATE TABLE ROOMS (
    ROOM_ID SERIAL PRIMARY KEY,
    ROOM_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    ROOM_TYPE VARCHAR(50) NOT NULL CHECK (ROOM_TYPE IN ('GENERAL', 'SEMI_PRIVATE', 'PRIVATE', 'ICU', 'OPERATION', 'EMERGENCY')),
    DEPT_ID INT,
    FLOOR INT DEFAULT 1,
    CAPACITY INT DEFAULT 1,
    RENT_PER_DAY NUMERIC(10,2) DEFAULT 0,
    FACILITIES TEXT, -- JSON array
    STATUS VARCHAR(20) DEFAULT 'AVAILABLE' CHECK (STATUS IN ('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', 'RESERVED')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ROOMS_DEPT FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID)
);

CREATE TRIGGER trg_rooms_updated 
BEFORE UPDATE ON ROOMS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 9. BEDS TABLE
-- =====================================================
CREATE TABLE BEDS (
    BED_ID SERIAL PRIMARY KEY,
    BED_NUMBER VARCHAR(20) NOT NULL,
    ROOM_ID INT NOT NULL,
    BED_TYPE VARCHAR(30) DEFAULT 'STANDARD' CHECK (BED_TYPE IN ('STANDARD', 'ELECTRIC', 'ICU', 'PEDIATRIC')),
    STATUS VARCHAR(20) DEFAULT 'AVAILABLE' CHECK (STATUS IN ('AVAILABLE', 'OCCUPIED', 'MAINTENANCE', 'RESERVED')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BEDS_ROOM FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID) ON DELETE CASCADE,
    CONSTRAINT UQ_BED_ROOM UNIQUE (BED_NUMBER, ROOM_ID)
);

CREATE TRIGGER trg_beds_updated 
BEFORE UPDATE ON BEDS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 10. PATIENT_BEDS TABLE (Bed Assignments)
-- =====================================================
CREATE TABLE PATIENT_BEDS (
    ASSIGNMENT_ID SERIAL PRIMARY KEY,
    PATIENT_ID INT NOT NULL,
    BED_ID INT NOT NULL,
    ASSIGNED_DATE TIMESTAMP NOT NULL,
    DISCHARGE_DATE TIMESTAMP,
    NOTES TEXT,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'DISCHARGED')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PB_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
    CONSTRAINT FK_PB_BED FOREIGN KEY (BED_ID) REFERENCES BEDS(BED_ID)
);

CREATE TRIGGER trg_patient_beds_updated 
BEFORE UPDATE ON PATIENT_BEDS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 11. APPOINTMENTS TABLE
-- =====================================================
CREATE TABLE APPOINTMENTS (
    APPOINTMENT_ID SERIAL PRIMARY KEY,
    APPOINTMENT_CODE VARCHAR(20) NOT NULL UNIQUE,
    PATIENT_ID INT NOT NULL,
    DOCTOR_ID INT NOT NULL,
    APPOINTMENT_DATE TIMESTAMP NOT NULL,
    APPOINTMENT_TIME VARCHAR(5) NOT NULL, -- Format: HH24:MI
    DURATION INT DEFAULT 30, -- in minutes
    TYPE VARCHAR(30) DEFAULT 'CONSULTATION' CHECK (TYPE IN ('CONSULTATION', 'FOLLOW_UP', 'EMERGENCY', 'SURGERY', 'CHECKUP')),
    STATUS VARCHAR(20) DEFAULT 'SCHEDULED' CHECK (STATUS IN ('SCHEDULED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
    REASON VARCHAR(500),
    NOTES TEXT,
    CREATED_BY INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_APPT_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
    CONSTRAINT FK_APPT_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID),
    CONSTRAINT FK_APPT_CREATOR FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID)
);

CREATE TRIGGER trg_appointments_updated 
BEFORE UPDATE ON APPOINTMENTS FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 12. INVOICES TABLE
-- =====================================================
CREATE TABLE INVOICES (
    INVOICE_ID SERIAL PRIMARY KEY,
    INVOICE_NUMBER VARCHAR(30) NOT NULL UNIQUE,
    PATIENT_ID INT NOT NULL,
    APPOINTMENT_ID INT,
    ISSUE_DATE TIMESTAMP NOT NULL,
    DUE_DATE TIMESTAMP NOT NULL,
    SUBTOTAL NUMERIC(12,2) DEFAULT 0,
    TAX_AMOUNT NUMERIC(12,2) DEFAULT 0,
    DISCOUNT_AMOUNT NUMERIC(12,2) DEFAULT 0,
    TOTAL_AMOUNT NUMERIC(12,2) DEFAULT 0,
    PAID_AMOUNT NUMERIC(12,2) DEFAULT 0,
    BALANCE_AMOUNT NUMERIC(12,2) DEFAULT 0,
    STATUS VARCHAR(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED')),
    NOTES TEXT,
    CREATED_BY INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_INV_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
    CONSTRAINT FK_INV_APPOINTMENT FOREIGN KEY (APPOINTMENT_ID) REFERENCES APPOINTMENTS(APPOINTMENT_ID),
    CONSTRAINT FK_INV_CREATOR FOREIGN KEY (CREATED_BY) REFERENCES USERS(USER_ID)
);

CREATE TRIGGER trg_invoices_updated 
BEFORE UPDATE ON INVOICES FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 13. INVOICE_ITEMS TABLE
-- =====================================================
CREATE TABLE INVOICE_ITEMS (
    ITEM_ID SERIAL PRIMARY KEY,
    INVOICE_ID INT NOT NULL,
    ITEM_TYPE VARCHAR(50) NOT NULL CHECK (ITEM_TYPE IN ('CONSULTATION', 'PROCEDURE', 'MEDICATION', 'ROOM_CHARGE', 'LAB_TEST', 'OTHER')),
    DESCRIPTION VARCHAR(255) NOT NULL,
    QUANTITY INT DEFAULT 1,
    UNIT_PRICE NUMERIC(10,2) NOT NULL,
    TOTAL_PRICE NUMERIC(10,2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ITEM_INVOICE FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES(INVOICE_ID) ON DELETE CASCADE
);

-- =====================================================
-- 14. BILLING_PAYMENTS TABLE
-- =====================================================
CREATE TABLE BILLING_PAYMENTS (
    PAYMENT_ID SERIAL PRIMARY KEY,
    INVOICE_ID INT NOT NULL,
    PAYMENT_DATE TIMESTAMP NOT NULL,
    PAYMENT_AMOUNT NUMERIC(12,2) NOT NULL,
    PAYMENT_METHOD VARCHAR(30) NOT NULL CHECK (PAYMENT_METHOD IN ('CASH', 'CARD', 'CHECK', 'BANK_TRANSFER', 'INSURANCE', 'ONLINE')),
    TRANSACTION_ID VARCHAR(100),
    NOTES TEXT,
    CREATED_BY INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PAYMENT_INVOICE FOREIGN KEY (INVOICE_ID) REFERENCES INVOICES(INVOICE_ID)
);

-- =====================================================
-- CREATE INDEXES FOR PERFORMANCE
-- =====================================================

CREATE INDEX IDX_USERS_ROLE ON USERS(ROLE_ID);
CREATE INDEX IDX_USERS_STATUS ON USERS(STATUS);
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);

CREATE INDEX IDX_DOCTORS_DEPT ON DOCTORS(DEPT_ID);
CREATE INDEX IDX_DOCTORS_STATUS ON DOCTORS(STATUS);
CREATE INDEX IDX_DOCTORS_SPECIALIZATION ON DOCTORS(SPECIALIZATION);

CREATE INDEX IDX_PATIENTS_DOCTOR ON PATIENTS(ASSIGNED_DOCTOR_ID);
CREATE INDEX IDX_PATIENTS_STATUS ON PATIENTS(STATUS);
CREATE INDEX IDX_PATIENTS_NAME ON PATIENTS(FIRST_NAME, LAST_NAME);
CREATE INDEX IDX_PATIENTS_PHONE ON PATIENTS(PHONE);

CREATE INDEX IDX_APPTS_PATIENT ON APPOINTMENTS(PATIENT_ID);
CREATE INDEX IDX_APPTS_DOCTOR ON APPOINTMENTS(DOCTOR_ID);
CREATE INDEX IDX_APPTS_DATE ON APPOINTMENTS(APPOINTMENT_DATE);
CREATE INDEX IDX_APPTS_STATUS ON APPOINTMENTS(STATUS);

CREATE INDEX IDX_HISTORY_PATIENT ON MEDICAL_HISTORY(PATIENT_ID);
CREATE INDEX IDX_HISTORY_DATE ON MEDICAL_HISTORY(VISIT_DATE);

CREATE INDEX IDX_BEDS_ROOM ON BEDS(ROOM_ID);
CREATE INDEX IDX_BEDS_STATUS ON BEDS(STATUS);
CREATE INDEX IDX_ROOMS_STATUS ON ROOMS(STATUS);
CREATE INDEX IDX_ROOMS_TYPE ON ROOMS(ROOM_TYPE);

CREATE INDEX IDX_INVOICES_PATIENT ON INVOICES(PATIENT_ID);
CREATE INDEX IDX_INVOICES_STATUS ON INVOICES(STATUS);
CREATE INDEX IDX_INVOICES_DATE ON INVOICES(ISSUE_DATE);
CREATE INDEX IDX_PAYMENTS_INVOICE ON BILLING_PAYMENTS(INVOICE_ID);

-- =====================================================
-- CREATE VIEWS FOR REPORTING
-- =====================================================

CREATE OR REPLACE VIEW V_DASHBOARD_STATS AS
SELECT
    (SELECT COUNT(*) FROM PATIENTS WHERE STATUS = 'INPATIENT') AS TOTAL_INPATIENTS,
    (SELECT COUNT(*) FROM PATIENTS) AS TOTAL_PATIENTS,
    (SELECT COUNT(*) FROM DOCTORS WHERE STATUS = 'ACTIVE') AS TOTAL_DOCTORS,
    (SELECT COUNT(*) FROM APPOINTMENTS WHERE DATE(APPOINTMENT_DATE) = CURRENT_DATE) AS TODAY_APPOINTMENTS,
    (SELECT COUNT(*) FROM APPOINTMENTS WHERE APPOINTMENT_DATE >= CURRENT_DATE AND APPOINTMENT_DATE < CURRENT_DATE + INTERVAL '1 day') AS TOTAL_APPOINTMENTS,
    (SELECT COALESCE(SUM(TOTAL_AMOUNT), 0) FROM INVOICES WHERE DATE(ISSUE_DATE) = CURRENT_DATE) AS TODAY_REVENUE,
    (SELECT COALESCE(SUM(TOTAL_AMOUNT), 0) FROM INVOICES WHERE ISSUE_DATE >= DATE_TRUNC('month', CURRENT_DATE)) AS MONTH_REVENUE,
    (SELECT COUNT(*) FROM BEDS WHERE STATUS = 'OCCUPIED') AS OCCUPIED_BEDS,
    (SELECT COUNT(*) FROM BEDS) AS TOTAL_BEDS;

CREATE OR REPLACE VIEW V_PATIENT_DETAILS AS
SELECT
    P.*,
    U.FIRST_NAME || ' ' || U.LAST_NAME AS DOCTOR_NAME,
    D.SPECIALIZATION AS DOCTOR_SPECIALIZATION,
    DEPT.DEPT_NAME
FROM PATIENTS P
LEFT JOIN DOCTORS D ON P.ASSIGNED_DOCTOR_ID = D.DOCTOR_ID
LEFT JOIN USERS U ON D.USER_ID = U.USER_ID
LEFT JOIN DEPARTMENTS DEPT ON D.DEPT_ID = DEPT.DEPT_ID;

CREATE OR REPLACE VIEW V_APPOINTMENT_DETAILS AS
SELECT
    A.*,
    P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME,
    P.PHONE AS PATIENT_PHONE,
    P.GENDER AS PATIENT_GENDER,
    U.FIRST_NAME || ' ' || U.LAST_NAME AS DOCTOR_NAME,
    D.SPECIALIZATION AS DOCTOR_SPECIALIZATION,
    DEPT.DEPT_NAME
FROM APPOINTMENTS A
JOIN PATIENTS P ON A.PATIENT_ID = P.PATIENT_ID
JOIN DOCTORS D ON A.DOCTOR_ID = D.DOCTOR_ID
JOIN USERS U ON D.USER_ID = U.USER_ID
LEFT JOIN DEPARTMENTS DEPT ON D.DEPT_ID = DEPT.DEPT_ID;

CREATE OR REPLACE VIEW V_BED_OCCUPANCY AS
SELECT
    R.ROOM_ID,
    R.ROOM_NUMBER,
    R.ROOM_TYPE,
    R.FLOOR,
    R.RENT_PER_DAY,
    B.BED_ID,
    B.BED_NUMBER,
    B.STATUS AS BED_STATUS,
    PB.PATIENT_ID,
    P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME,
    PB.ASSIGNED_DATE,
    PB.DISCHARGE_DATE AS EXPECTED_DISCHARGE
FROM ROOMS R
JOIN BEDS B ON R.ROOM_ID = B.ROOM_ID
LEFT JOIN PATIENT_BEDS PB ON B.BED_ID = PB.BED_ID AND PB.STATUS = 'ACTIVE'
LEFT JOIN PATIENTS P ON PB.PATIENT_ID = P.PATIENT_ID;

CREATE OR REPLACE VIEW V_REVENUE_SUMMARY AS
SELECT
    I.INVOICE_ID,
    I.INVOICE_NUMBER,
    I.ISSUE_DATE,
    I.TOTAL_AMOUNT,
    I.PAID_AMOUNT,
    I.BALANCE_AMOUNT,
    I.STATUS,
    P.FIRST_NAME || ' ' || P.LAST_NAME AS PATIENT_NAME,
    P.PATIENT_CODE,
    COALESCE(SUM(PAY.PAYMENT_AMOUNT), 0) AS TOTAL_PAYMENTS
FROM INVOICES I
JOIN PATIENTS P ON I.PATIENT_ID = P.PATIENT_ID
LEFT JOIN BILLING_PAYMENTS PAY ON I.INVOICE_ID = PAY.INVOICE_ID
GROUP BY I.INVOICE_ID, I.INVOICE_NUMBER, I.ISSUE_DATE, I.TOTAL_AMOUNT,
         I.PAID_AMOUNT, I.BALANCE_AMOUNT, I.STATUS, P.FIRST_NAME, P.LAST_NAME, P.PATIENT_CODE;  

CREATE OR REPLACE VIEW V_DOCTOR_PERFORMANCE AS  
SELECT
    D.DOCTOR_ID,
    U.FIRST_NAME || ' ' || U.LAST_NAME AS DOCTOR_NAME,
    D.SPECIALIZATION,
    DEPT.DEPT_NAME,
    D.PATIENTS_SEEN,
    D.EXPERIENCE_YEARS,
    (SELECT COUNT(*) FROM PATIENTS WHERE ASSIGNED_DOCTOR_ID = D.DOCTOR_ID) AS ASSIGNED_PATIENTS,
    (SELECT COUNT(*) FROM APPOINTMENTS WHERE DOCTOR_ID = D.DOCTOR_ID AND STATUS = 'COMPLETED') AS COMPLETED_APPOINTMENTS,
    (SELECT COALESCE(SUM(I.TOTAL_AMOUNT), 0) 
     FROM INVOICES I
     JOIN APPOINTMENTS A ON I.APPOINTMENT_ID = A.APPOINTMENT_ID
     WHERE A.DOCTOR_ID = D.DOCTOR_ID) AS TOTAL_REVENUE
FROM DOCTORS D
JOIN USERS U ON D.USER_ID = U.USER_ID
LEFT JOIN DEPARTMENTS DEPT ON D.DEPT_ID = DEPT.DEPT_ID
WHERE D.STATUS = 'ACTIVE';

-- =====================================================
-- 15. NOTIFICATIONS TABLE
-- =====================================================
CREATE TABLE NOTIFICATIONS (
    NOTIFICATION_ID SERIAL PRIMARY KEY,
    USER_ID INT,
    TITLE VARCHAR(100) NOT NULL,
    MESSAGE TEXT NOT NULL,
    TYPE VARCHAR(20) DEFAULT 'INFO' CHECK (TYPE IN ('INFO', 'SUCCESS', 'WARNING', 'ERROR')),
    IS_READ INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_NOTIFICATION_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_NOTIFICATIONS_USER ON NOTIFICATIONS(USER_ID);
CREATE INDEX IDX_NOTIFICATIONS_READ ON NOTIFICATIONS(IS_READ);

